<?php

use Yivic\YivicKernelTheme\App\Support\YivicKernelThemeHelper;

return [

    /*
    |--------------------------------------------------------------------------
    | Application Name
    |--------------------------------------------------------------------------
    |
    | This value is the name of your application. It is used when the
    | framework needs to place the application's name in notifications
    | or any other location as required by the application or its packages.
    |
    */

    'name' => defined('YIVIC_KERNEL_THEME_APP_NAME')
        ? YIVIC_KERNEL_THEME_APP_NAME
        : (defined('WP_APP_NAME') ? WP_APP_NAME : 'Yivic Kernel Theme Web App'),

    /*
    |--------------------------------------------------------------------------
    | Application Environment
    |--------------------------------------------------------------------------
    |
    | This value determines the "environment" your application is currently
    | running in. You may set this in your "wp-config.php" or ".env" file.
    |
    */

    'env' => defined('WP_ENV') ? WP_ENV : 'production',

    /*
    |--------------------------------------------------------------------------
    | Application Debug Mode
    |--------------------------------------------------------------------------
    |
    | When your application is in debug mode, detailed error messages with
    | stack traces will be shown on every error that occurs within your
    | application. If disabled, a simple generic error page is shown.
    |
    */

    'debug' => defined('WP_DEBUG') ? (bool) WP_DEBUG : false,

    /*
    |--------------------------------------------------------------------------
    | Application URL
    |--------------------------------------------------------------------------
    |
    | This URL is used by the console to properly generate URLs when using
    | CLI tools. You should set this to the root URL of your site.
    |
    */

    'url' => defined('WP_SITEURL') ? WP_SITEURL : site_url(),

    /*
    |--------------------------------------------------------------------------
    | Application Asset URL
    |--------------------------------------------------------------------------
    |
    | This URL is used as the base for all public assets generated by the
    | wp-app layer (CSS, JS, images, etc.).
    |
    */

    'asset_url' => YivicKernelThemeHelper::wp_app_get_asset_url(true),

    /*
    |--------------------------------------------------------------------------
    | Application Timezone
    |--------------------------------------------------------------------------
    |
    | Here you may specify the default timezone for your application, which
    | will be used by the PHP date and date-time functions.
    |
    */

    'timezone' => YivicKernelThemeHelper::wp_app_get_timezone(),

    /*
    |--------------------------------------------------------------------------
    | Application Locale Configuration
    |--------------------------------------------------------------------------
    |
    | The application locale determines the default locale that will be used
    | by the translation service provider.
    |
    */

    'locale' => get_locale(),

    /*
    |--------------------------------------------------------------------------
    | Application Fallback Locale
    |--------------------------------------------------------------------------
    |
    | The fallback locale is used when the current one is not available.
    |
    */

    'fallback_locale' => 'en_US',

    /*
    |--------------------------------------------------------------------------
    | Faker Locale
    |--------------------------------------------------------------------------
    |
    | This locale will be used by the Faker PHP library when generating fake
    | data for your database seeds.
    |
    */

    'faker_locale' => get_locale(),

    /*
    |--------------------------------------------------------------------------
    | Encryption Key
    |--------------------------------------------------------------------------
    |
    | This key is used by the encrypter service and should be set to a random,
    | 32 character string. WPApplication will automatically generate and
    | persist a key in the "yivic_kernel_theme_wp_app_auth_key" option when
    | this value is empty.
    |
    */

    'key' => defined('YIVIC_KERNEL_THEME_APP_KEY')
        ? YIVIC_KERNEL_THEME_APP_KEY
        : (string) get_option('yivic_kernel_theme_wp_app_auth_key', ''),

    'cipher' => 'AES-256-CBC',

    /*
    |--------------------------------------------------------------------------
    | Autoloaded Service Providers
    |--------------------------------------------------------------------------
    |
    | These service providers will be automatically loaded on the request
    | to your application.
    |
    */

    'providers' => [
        // Core Laravel-style providers (adapt / prune as needed).
    ],

    /*
    |--------------------------------------------------------------------------
    | Class Aliases
    |--------------------------------------------------------------------------
    |
    | This array of class aliases will be registered when the application
    | is started. However, they are "lazy" loaded, so they do not hinder
    | performance.
    |
    */

    'aliases' => [],
];